#!/bin/bash
# Quick Render Deployment Checklist

echo "=================================================="
echo "🚀 LANE GOOGLE - RENDER DEPLOYMENT CHECKLIST"
echo "=================================================="
echo ""
echo "✅ CODE FIXES APPLIED:"
echo "  • src/api/campaign_analytics_api.py - Auth imports fixed"
echo "  • src/api/keyword_analytics_api.py - Auth imports fixed"
echo "  • src/config/settings.py - Changed to OpenRouter config"
echo ""
echo "=================================================="
echo "📋 RENDER ENVIRONMENT VARIABLES TO UPDATE:"
echo "=================================================="
echo ""
echo "1. FIX THIS TRUNCATED VALUE:"
echo "   GOOGLE_ADS_CLIENT_ID=756901677789-lak300g2plkl57sdqn2ndvr005mp7tqm.apps.googleusercontent.com"
echo "   (You currently have it ending with '.apps.googleuse' - WRONG!)"
echo ""
echo "2. ADD THESE NEW VARIABLES:"
echo "   ENVIRONMENT=production"
echo "   SECRET_KEY=10b8f18f5519885649d3242b8c276679a7f83d3bbc011d6f232cdb00020a3810"
echo "   JWT_SECRET_KEY=5b109c5d7680161bbd00485e9313ded4f2a0332254b612b1ab08428ee8ad7088"
echo ""
echo "3. KEEP YOUR EXISTING (correct) VARIABLES:"
echo "   OPENROUTER_API_KEY=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"
echo "   (No need for OPENAI_API_KEY - you're using OpenRouter!)"
echo ""
echo "=================================================="
echo "📝 GIT COMMANDS TO RUN:"
echo "=================================================="
echo ""
echo "cd /Users/copp1723/Desktop/lane_google"
echo "git add -A"
echo 'git commit -m "Fix auth imports and configure OpenRouter instead of OpenAI"'
echo "git push origin main"
echo ""
echo "=================================================="
echo "✨ After updating Render env vars and pushing code,"
echo "   Render will auto-deploy with all fixes applied!"
echo "=================================================="
