# Render deployment configuration for Lane MCP
services:
  # Backend API Service
  - type: web
    name: lane-mcp-api
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r config/requirements.txt
    startCommand: python -m gunicorn -w 4 -b 0.0.0.0:$PORT src.main_production:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lane-mcp-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: lane-mcp-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      # Google Ads API Configuration - Set these in Render Dashboard
      - key: GOOGLE_ADS_DEVELOPER_TOKEN
        sync: false
      - key: GOOGLE_ADS_CLIENT_ID
        sync: false
      - key: GOOGLE_ADS_CLIENT_SECRET
        sync: false
      - key: GOOGLE_ADS_REFRESH_TOKEN
        sync: false
      # OpenRouter API Configuration - Set in Render Dashboard
      - key: OPENROUTER_API_KEY
        sync: false

  # Redis for caching and sessions
  - type: redis
    name: lane-mcp-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

# Database
databases:
  - name: lane-mcp-db
    databaseName: lane_mcp_production
    plan: free
    postgresMajorVersion: 15